apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "book-catalogue.fullname" . }}-config
  labels:
    {{- include "book-catalogue.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
  DEBUG: {{ .Values.env.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  # Add more non-sensitive environment variables as needed 