apiVersion: v1
kind: Secret
metadata:
  name: {{ include "book-catalogue.fullname" . }}-secret
  labels:
    {{- include "book-catalogue.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  EMAIL_HOST_USER: {{ .Values.secrets.EMAIL_HOST_USER | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.EMAIL_HOST_PASSWORD | b64enc | quote }}
  # Add more secrets as needed 