services:
  web:
    build: .
    command: gunicorn sba24070_book_catalogue.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sba24070
      - POSTGRES_USER=sba24070_user
      - POSTGRES_PASSWORD=your_secure_password

volumes:
  postgres_data: 