# Generated by Django 5.2.4 on 2025-07-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to='books.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
