# Generated by Django 4.2.23 on 2025-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_added_by_book_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the book.', null=True, upload_to='book_covers/'),
        ),
    ]
