# Generated by Django 4.2.23 on 2025-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_referral',
            field=models.CharField(blank=True, help_text='Admin referral or notes for this user.', max_length=255, null=True),
        ),
    ]
