# Generated by Django 5.2.4 on 2025-07-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_user_admin_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_notes',
            field=models.TextField(blank=True, help_text='User personal notes or referral info.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_referral',
            field=models.ForeignKey(blank=True, help_text='Book selected by admin as a referral for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='books.book'),
        ),
    ]
