# configmap.yaml
# This Kubernetes ConfigMap stores non-sensitive environment variables for Django and Postgres.
# Use this for settings that are not secrets, such as debug flags and connection info.
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
    purpose: environment
    managed-by: user
    # Stores Django and Postgres non-secret config
    # Update values as needed
    #
data:
  DEBUG: "False"                  # Set to "True" for development
  POSTGRES_HOST: "postgres"       # Hostname of the Postgres service (should match the service name)
  POSTGRES_PORT: "5432"           # Default Postgres port 