# postgres-deployment.yaml
# This file contains both the Deployment and Service for a Postgres database in Kubernetes.
# It is intended for local development or testing. For production, use a managed database service.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    managed-by: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: POSTGRES_PASSWORD
        # For persistent storage, add a volumeMount and PersistentVolumeClaim here
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    managed-by: user
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432 