# secret.yaml
# This Kubernetes Secret stores sensitive environment variables for Django and Postgres.
# Values must be base64-encoded. Use: echo -n 'value' | base64
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    app: django
    purpose: environment
    managed-by: user
    # Stores Django and Postgres secrets
    # Do NOT commit real secrets to public repos
    # Update values as needed
    #
type: Opaque
data:
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk=           # supersecretkey
  POSTGRES_DB: Ym9va2Ri                      # bookdb
  POSTGRES_USER: YWRtaW4=                    # admin
  POSTGRES_PASSWORD: cGFzc3dvcmQ=            # password 