# secret.yaml
# This Kubernetes Secret stores sensitive environment variables for Django and Postgres.
# Values must be base64-encoded. Use: echo -n 'value' | base64
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    app: django
    purpose: environment
    managed-by: user
    # Stores Django and Postgres secrets
    # Do NOT commit real secrets to public repos
    # Update values as needed
    #
type: Opaque
data:
  SECRET_KEY: RnFJazZIQi1FTEZyczdYbk9QVmYzdEFmRlhNVXRfZ05lVUtUSlZYTkJhLUlyZnNqY0VJVVJBb0NfU3NSOE15eS1jaw==
  POSTGRES_DB: c2JhMjQwNzA=
  POSTGRES_USER: c2JhMjQwNzBfdXNlcg==
  POSTGRES_PASSWORD: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
        # password 