# secret.example.yaml
# Copy this file to secret.yaml and fill in your own base64-encoded secrets.
# Use: echo -n 'yourvalue' | base64
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    app: django
    purpose: environment
    managed-by: user
type: Opaque
data:
  SECRET_KEY: dXNlcl9zZWNyZXRfa2V5  # user_secret_key
  POSTGRES_DB: ZGJfbmFtZQ==         # db_name
  POSTGRES_USER: ZGJfdXNlcg==       # db_user
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # password 