# service.yaml
# This Kubernetes Service exposes the Django application to the network.
# It maps port 80 on the cluster to port 8000 in the Django container.
# Use NodePort for local clusters, or change to LoadBalancer for cloud environments.
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
    managed-by: user
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80         # Exposed port on the cluster
      targetPort: 8000 # Port Django runs on in the container
  type: NodePort      # Change to LoadBalancer if deploying to cloud 