name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - name: Run Django tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        run: python manage.py test

  runmigrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - name: Run django migrate
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        run: python manage.py migrate

  migrations-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - name: Run makemigrations --check
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        run: python manage.py makemigrations --check

  migrations-merge-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - name: Run makemigrations --merge --check
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        run: python manage.py makemigrations --merge --check

  docker:
    needs: [test, runmigrations, migrations-check, migrations-merge-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-book-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
      - name: Test kubectl access
        run: kubectl get nodes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/django-deployment django=${{ secrets.DOCKER_USERNAME }}/devops-book-app:latest
          kubectl rollout status deployment/django-deployment 

  helm-deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
      - name: Test kubectl access
        run: kubectl get nodes
      - name: Helm upgrade/install
        run: |
          helm upgrade --install book-catalogue ./book-catalogue \
            --namespace default \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/devops-book-app \
            --set image.tag=latest \
            --set secrets.SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --set secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --set secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --set secrets.EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} \
            --set secrets.EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
            --wait 

  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - run: coverage run manage.py test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
      - run: coverage report
      - run: coverage xml
      

  type-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sba24070_user" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: pip install mypy
      - name: Set DB host to localhost for CI
        run: python3 custom_scripts/host_helper.py <<< "1"
      - run: mypy .
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: sba24070
          POSTGRES_USER: sba24070_user
          POSTGRES_PASSWORD: your_secure_password

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8 and save output
        run: |
          flake8 . > flake8.txt || true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build mkdocs and save output
        run: |
          mkdocs build > mkdocs.txt 2>&1 || true 